-- DropForeignKey
ALTER TABLE "INGRESOS" DROP CONSTRAINT "INGRESOS_codigo_qr_id_fkey";
-- DropForeignKey
ALTER TABLE "INGRESOS" DROP CONSTRAINT "INGRESOS_visitante_id_fkey";
-- DropForeignKey
ALTER TABLE "PAGOS" DROP CONSTRAINT "PAGOS_alicuota_id_fkey";

-- AlterTable CODIGOS_QR
ALTER TABLE "CODIGOS_QR" DROP COLUMN "fecha_expiracion",
ADD COLUMN "fecha_inicio" TIMESTAMP(3) NOT NULL DEFAULT now(),
ADD COLUMN "fecha_fin" TIMESTAMP(3) NOT NULL DEFAULT now() + interval '4 hours';
ALTER TABLE "CODIGOS_QR" ALTER COLUMN "fecha_inicio" DROP DEFAULT;
ALTER TABLE "CODIGOS_QR" ALTER COLUMN "fecha_fin" DROP DEFAULT;

-- AlterTable INGRESOS
ALTER TABLE "INGRESOS" ADD COLUMN "cedula_visitante" VARCHAR(20),
ADD COLUMN "placa_vehiculo" VARCHAR(10),
ADD COLUMN "tipo_ingreso" VARCHAR(20) NOT NULL DEFAULT 'automatico',
ALTER COLUMN "codigo_qr_id" DROP NOT NULL,
ALTER COLUMN "visitante_id" DROP NOT NULL;

-- AlterTable PAGOS
ALTER TABLE "PAGOS" DROP COLUMN "alicuota_id",
ADD COLUMN "cantidad_meses" INTEGER,
ADD COLUMN "monto_pagado" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "PAGOS" ALTER COLUMN "monto_pagado" DROP DEFAULT;

-- AlterTable VISITANTES
ALTER TABLE "VISITANTES" ADD COLUMN "placa_vehiculo" VARCHAR(10);

-- CreateTable PAGOS_ALICUOTAS
CREATE TABLE "PAGOS_ALICUOTAS" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "pago_id" UUID NOT NULL,
    "alicuota_id" UUID NOT NULL,
    CONSTRAINT "PAGOS_ALICUOTAS_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PAGOS_ALICUOTAS_pago_id_alicuota_id_key" ON "PAGOS_ALICUOTAS"("pago_id", "alicuota_id");

-- AddForeignKey
ALTER TABLE "INGRESOS" ADD CONSTRAINT "INGRESOS_codigo_qr_id_fkey" FOREIGN KEY ("codigo_qr_id") REFERENCES "CODIGOS_QR"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "INGRESOS" ADD CONSTRAINT "INGRESOS_visitante_id_fkey" FOREIGN KEY ("visitante_id") REFERENCES "VISITANTES"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PAGOS_ALICUOTAS" ADD CONSTRAINT "PAGOS_ALICUOTAS_pago_id_fkey" FOREIGN KEY ("pago_id") REFERENCES "PAGOS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PAGOS_ALICUOTAS" ADD CONSTRAINT "PAGOS_ALICUOTAS_alicuota_id_fkey" FOREIGN KEY ("alicuota_id") REFERENCES "ALICUOTAS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;