-- DropForeignKey
ALTER TABLE "INGRESOS" DROP CONSTRAINT "INGRESOS_bitacora_id_fkey";

-- AlterTable
ALTER TABLE "INGRESOS" ALTER COLUMN "bitacora_id" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "INGRESOS" ADD CONSTRAINT "INGRESOS_bitacora_id_fkey" FOREIGN KEY ("bitacora_id") REFERENCES "BITACORA_TURNOS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
