-- DropForeignKey
ALTER TABLE "INGRESOS" DROP CONSTRAINT "INGRESOS_residente_id_fkey";

-- AlterTable
ALTER TABLE "INGRESOS" ALTER COLUMN "residente_id" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "INGRESOS" ADD CONSTRAINT "INGRESOS_residente_id_fkey" FOREIGN KEY ("residente_id") REFERENCES "RESIDENTES"("id") ON DELETE SET NULL ON UPDATE CASCADE;
